### ISSUE TITLE
Taulink settings do not populate

### ISSUE THREAD

**Issue by carbogit** [TauLabs/TauLabs#1555] opened 2015-04-12 16:49 UTC
First, I am assuming that the OPlink Mini I have is treated as a Taulink. Using the Rf bind wizard, I have established a working link between Oplm and Revomini:

![desktop2015-04-12 18_43_18](https://cloud.githubusercontent.com/assets/5855347/7106541/793218c6-e144-11e4-994f-f517903e59c6.png)

However, the settings for Hwtaulink do not populate, so I can't make manual changes without the wizard:

![desktop2015-04-12 18_40_24](https://cloud.githubusercontent.com/assets/5855347/7106544/91a8cee0-e144-11e4-9046-1a915c0a8b08.png)

![desktop2015-04-12 18_40_48](https://cloud.githubusercontent.com/assets/5855347/7106545/98568458-e144-11e4-8547-3badefadfeea.png)

**Comment by peabody124** [comment] 2015-04-13 03:00
Yeah because of the interaction of the "SessionManaging" system the GCS doesn't know that HWTauLink exists and doesn't notice it. You can fetch the settings and it should show you the latest. Glad to hear the binding wizard is working for you.

**Comment by carbogit** [comment] 2015-04-15 22:14
Yes, bind wizard is working fine, a really nice solution.
Fetching settings does work (had GCS crash when doing that before, but not anymore), so problem solved.

One more thing, already posted on the forums. The coordID field does not accept the last digit in most hex IDs when working manually in the object browser.

1234567890 can be entered, but not
2358626261 which is my coordinator modem

**Comment by peabody124** [comment] 2015-04-15 23:01
Could you open a separate issue for that? It is a general bug in the UAVObjectBrowser that I would like to fix about limited digits. It doesn't handle negative numbers either IIRC.

**Comment by mlyle** [comment] 2015-08-28 21:44
As designed-- closing.

**Closed by mlyle** 2015-08-28 21:44 UTC
