### ISSUE TITLE
Welcome buttons not working after switching to different tab and back

### ISSUE THREAD

**Issue by ulab** [TauLabs/TauLabs#1486] opened 2015-02-08 11:08 UTC
I'm running TauLabs master: 20150131-4082e9d8 on OS X 10.10.2 from a terminal using
```
rm -r ~/.config/TauLabs/; /Applications/Tau\ Labs\ GCS.app/Contents/MacOS/Tau\ Labs\ GCS
```
There's no board connected.

After switching to a different tab and going back to the welcome screen, neither of the "buttons" work anymore.

**Comment by kubark42** [comment] 2015-10-01 16:22
Unable to reproduce on OS X 10.10.4. There's not been much traffic on this bug, so assuming that it has been fixed in the latest master, or was machine dependent.

@ulab please reopen this if there is additional data, or the problem still persists.

**Closed by kubark42** 2015-10-01 16:22 UTC
Labels: bug, gcs
