### ISSUE TITLE
GCS Input (transmitter) calibration

### ISSUE THREAD

**Issue by xerovis** [TauLabs/TauLabs#999] opened 2013-10-19 23:14 UTC
When doing Input Configuration Wizard and get to the point of moving your sticks the GCS does not wait long enough or is too sensitive to stick movement. This results in the first input channel (throttle in my case) being essentially skipped. I have to push back so that I can setup that channel correctly.

Occurs in Master and Next.

**Comment by elafargue** [comment] 2015-03-26 03:22
Cannot reproduce in current GCS - issue is more than 1 year old,closing...

**Closed by elafargue** 2015-03-26 03:22 UTC
