### ISSUE TITLE
lag's with next_20150321

### ISSUE THREAD

**Issue by Zyamstein** [TauLabs/TauLabs#1512] opened 2015-03-22 19:58 UTC
windows 8.1
Videocard - Intel 4 series
taulabs next_20150321
disappear systemhealth and pfd gadgets
and
welcome screen lug https://yadi.sk/i/wCaUzfGsfSbXE

after clean configuration gadgets is back

**Comment by mlyle** [comment] 2015-06-18 16:53
Can you please provide more information?  The bug is for the GCS being laggy-- is this a regression from previous releases?  It looks like the linked picture is gone-- can you upload to Github?  Thanks!

**Comment by mlyle** [comment] 2015-07-03 19:51
Closed INVALID due to lack of details.

**Closed by mlyle** 2015-07-03 19:51 UTC
